# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userDash_app', '0002_user_description'),
        ('messageBoard', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='message_leaver',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='message_leaver', to='userDash_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_reciever',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='message_reciever', to='userDash_app.User'),
            preserve_default=False,
        ),
    ]
