# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageBoard', '0003_auto_20160630_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_leaver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_reciever',
        ),
    ]
