# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDash_app', '0002_user_description'),
        ('messageBoard', '0004_auto_20160630_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_leaver',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='message_leaver', to='userDash_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_reciever',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='message_reciever', to='userDash_app.User'),
            preserve_default=False,
        ),
    ]
