# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('messageBoard', '0005_auto_20160714_1442'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('messageManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('messageManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='attached_to_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messageBoard.Message'),
            preserve_default=False,
        ),
    ]
