# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userDash_app', '0002_user_description'),
        ('messageBoard', '0006_auto_20170202_1554'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('commentManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='board_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_leaver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_leaver', to='userDash_app.User'),
            preserve_default=False,
        ),
    ]
